language: node_js
node_js:
  - 10
  - 8
cache:
  directories:
    - node_modules/
notifications:
  email: false
# Retry install on fail to avoid failing a build on network/disk/external errors
install:
  - travis_retry npm install
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  only:
    - master